# Generated by Django 5.1.6 on 2025-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], max_length=50)),
                ('muscle_group', models.CharField(choices=[('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Piernas', 'Piernas'), ('Hombros', 'Hombros'), ('Brazos', 'Brazos'), ('Abdomen', 'Abdomen')], max_length=50)),
                ('equipment', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
